### ISSUE TITLE
php56u-pecl-krb5 broken dependency to libkadm5clnt_mit.so.8 on CentOS 7.5

### ISSUE THREAD

**Issue by joernott** [iuscommunity-pkg/php56u-pecl-krb5#1]
php${PHP_VERSION}-pecl-krb5 requires libkadm5clnt_mit.so.8. The only available package libkadm5-1.15.1-19.el7.x86_64 installs libkadm5clnt_mit.so.11.0 resulting in a broken dependency.

**Comment by carlwgeorge** [comment]
Thanks for the heads up. Fixed in f3371d314767f5c4f8253aaa530bff407ace7322, and available in ius-testing.
